[package]
name = "awriter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
actor_runtime = { version = "0.1.0", path = "../actor_runtime" }
actor_runtime_mocked = { version = "0.1.0", path = "../actor_runtime_mocked" }
