[package]
name = "ailets-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ailets-types = { path = "../ailets-types" }
serde.workspace = true
serde_json.workspace = true
