[package]
name = "messages_to_markdown"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
# To run tests, two types are needed
crate-type = ["cdylib", "lib"]
# crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.5.0"
getrandom = { version = "0.2", features = ["custom"] }
rjiter = { version = "1.0.0", path = "../../../streaming_json/rjiter" }
