[package]
name = "ailets-stdlib"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ailets-types = { path = "../ailets-types" }
ailets-runtime = { path = "../ailets-runtime" }
serde.workspace = true
serde_json.workspace = true
